### ISSUE TITLE
ct_2&5_1year.csv and pytorch3dunet/pretrained/r3d101_KM_200ep.pth

### ISSUE THREAD

**Issue by rookie688** [Tinysqua/GFE-Mamba#2]
Dear author,

Thank you very much for sharing your code. I am trying to reproduce your experiment, but I cannot find the file "ct_2&5_1year.csv","ct_2&5_3year.csv"and "pytorch3dunet/pretrained/r3d101_KM_200ep.pth" in the shared project,  Could you please share it with me? Thank you very much,my email is 1211758727li@gmail.com

**Comment by Tinysqua** [comment]
We are planning to upload ct_2&5_1year.csv and ct_2&5_3year.csv these days. As for the "pretrained/r3d101_KM_200ep.pth", we can't really recall where we use it. Is this file prevent the code from normal running process?

**Comment by guangqianyang** [comment]
> We are planning to upload ct_2&5_1year.csv and ct_2&5_3year.csv these days. As for the "pretrained/r3d101_KM_200ep.pth", we can't really recall where we use it. Is this file prevent the code from normal running process?

Same issue. Have you uploaded ct_2&5_1year.csv?

**Comment by Tinysqua** [comment]
@guangqianyang the table you mentioned has been updated by our research partners. Please check the folder named "GEF-Mamba_ADNI_Dataset", the README there in the subfolder will guide you.

**Comment by Tinysqua** [comment]
@guangqianyang if there are other questions, please inform me.
